# Python

In [1]:
print("Hello World!")

Hello World!


**Comments**

In [2]:
# this is a comment
"""
this is a long comment
"""

'\nthis is a long comment\n'

**Variable Assignment**

In [3]:
import numpy as np # matrix math library
import scipy.special as sp # scientific computing
x = 5.71
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(A)
I = sp.iv(x, A)
print(x,A,arr,I, sep='\n')

5.71
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4.70923380e-05 2.75296904e-03 3.34028974e-02]
 [2.20939866e-01 1.07390066e+00 4.36678176e+00]
 [1.58766383e+01 5.35980546e+01 1.71905963e+02]]


**String formatting**

In [4]:
A = np.pi * np.ones(3)
txt = "{:f} | {:.2f} | {:12f}".format(*A)
print(txt)

3.141593 | 3.14 |     3.141593


**User input**

In [ ]:
prompt = "Enter info: "
str_input = input(prompt)
print(str_input)

**Control Logic: If Statement**

In [ ]:
x = 3
if x > 5:
    y = 2
elif x < 0:
    y = 8
else:
    y = 24

In [ ]:
y

In [ ]:
x = 7
if x>5:
    y = 2
    if x<10:
        y = 8
else:
    y = 24

In [ ]:
y

**Control Logic: For Loop**

In [ ]:
x = np.ones(10)
for n in range(2,7):
    x[n] = 2 * x[n-1]

In [ ]:
n = range(2,7)
print(list(n))
n[3]
x

**Control Logic: While Loop**

In [ ]:
n = 1
nFactorial = 1
while nFactorial < 1e100:
    n+=1
    nFactorial*=n

In [ ]:
#python 3.6+ string formatting
f'{nFactorial:e}'

**Functions**

In [ ]:
def fact(n):
    f = np.prod(range(1, n+1))
    return f

In [ ]:
fact(10)

In [ ]:
def add2(x, y):
    a = x + 2;
    b = y + 2;
    return a, b

In [ ]:
c, d = add2(4, 5)
c, d

**Classes**

In [ ]:
import matplotlib.pyplot as plt

class Circle(object):
    def __init__(self, rad):
        if rad > 0:
            self.radius = rad;
        else:
            raise ValueError("Value must be positive")
    
    def area(self):
            return np.pi*self.radius**2
        
    def plotC(self, color):
        theta = np.linspace(-2*np.pi, 2*np.pi, 100)
        fig, ax = plt.subplots()
        ax.plot(self.radius*np.cos(theta), 
                self.radius*np.sin(theta), color=color)
        ax.set_aspect('equal')
        fig.show()

In [ ]:
c = Circle(2)
c.radius

In [ ]:
c.radius = 3
c.radius

In [ ]:
c.area()

In [ ]:
%matplotlib inline
c.plotC('green')

# Talk to Matlab:
https://www.mathworks.com/help/matlab/matlab-engine-for-python.html

# Translate lots of code
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html

## Examples/Questions

In [ ]:
# reading a file into a datastructure (data frame)
import pandas as pd
ds = pd.read_csv("../data/land_cover.csv")

In [ ]:
ds

In [ ]:
#creating a matrix
A = np.random.randint(-5, 6, 25).reshape((5,5))
A

In [ ]:
# plotting a matrix
plt.imshow(A, cmap='coolwarm')
plt.title("Random")

In [ ]:
# alternatively using object oriented
fig, ax = plt.subplots()
ax.imshow(A, cmap='coolwarm')
ax.set_title("Random")

In [ ]:
%whos